# Generated by Django 2.0.2 on 2019-02-03 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='adress',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='地址'),
        ),
    ]
